python race.py\
 --data_dir=/content/RACE \
 --bert_model=bert-base-uncased \
 --output_dir=large_models \
 --max_seq_length=256 \
 --do_train \
 --do_eval  \
 --do_lower_case \
 --train_batch_size=4 \
 --eval_batch_size=4 \
 --learning_rate=1e-5 \
 --num_train_epochs=2 \
 --gradient_accumulation_steps=1 \
 --loss_scale=0